# Generated by Django 6.0.5 on 2026-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemecustomer',
            name='payment_plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
