# Generated by Django 6.0.5 on 2026-05-16 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0002_alter_schemecustomer_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemecustomer',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
