# Generated by Django 6.0.5 on 2026-05-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0003_rename_total_price_sales_total_amount'),
        ('schemeapp', '0003_schemecustomer_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemegoodspickup',
            name='linked_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saleapp.sales'),
        ),
        migrations.AlterField(
            model_name='schemegoodspickup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleapp.product'),
        ),
        migrations.AlterField(
            model_name='schemegoodspickup',
            name='quantity_taken',
            field=models.PositiveIntegerField(),
        ),
    ]
