# Generated by Django 6.0.5 on 2026-05-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0004_alter_schemegoodspickup_linked_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemegoodspickup',
            old_name='product',
            new_name='product_name',
        ),
    ]
