# Generated by Django 6.0.5 on 2026-05-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemeapp', '0005_rename_product_schemegoodspickup_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemegoodspickup',
            old_name='product_name',
            new_name='product',
        ),
    ]
