# Generated by Django 6.0.5 on 2026-05-13 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('quantity_received', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('supplier_paid', models.BooleanField(default=False)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('re_order_level', models.IntegerField(default=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleapp.product')),
            ],
        ),
    ]
