# Generated by Django 6.0.3 on 2026-06-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
    ]
