# Generated by Django 6.0.5 on 2026-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='transport_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
