# Generated by Django 6.0.5 on 2026-05-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0002_sales_distance_sales_transport_sales_transport_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='total_price',
            new_name='total_amount',
        ),
    ]
