# Generated by Django 6.0.5 on 2026-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0005_sales_customer_name_alter_sales_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
