# Generated by Django 6.0.3 on 2026-06-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0006_saleitem_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
    ]
